### ISSUE TITLE
Error when starting up logging

### ISSUE THREAD

**Issue by CoreyBehrends** [sgargan/loggly-syslog-logback#1]
I love the simplicity of your code, very well done.  I'm getting an error perhaps you can help me with:

com.github.sgargan.logging.LogglySyslogAppender$LogglySyslogLayout(\"null\") - Empty or null pattern.

This occurs when my Spring Boot based app starts.  Any insight is greatly appreciated.  full stack trace below:

java.lang.IllegalStateException: java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in com.github.sgargan.logging.LogglySyslogAppender$LogglySyslogLayout("null") - Empty or null pattern.
ERROR in com.github.sgargan.logging.LogglySyslogAppender$LogglySyslogLayout("null") - Empty or null pattern.
    at org.springframework.boot.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:254)
    at org.springframework.boot.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:213)
    at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:188)
    at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:168)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:119)
    at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:111)
    at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:65)
    at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
    at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:324)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:295)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1085)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1074)
    at com.proathleteinc.productcatalog.Application.main(Application.java:21)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in com.github.sgargan.logging.LogglySyslogAppender$LogglySyslogLayout("null") - Empty or null pattern.
ERROR in com.github.sgargan.logging.LogglySyslogAppender$LogglySyslogLayout("null") - Empty or null pattern.
    at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:153)
    at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithSpecificConfig(AbstractLoggingSystem.java:56)
    at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:46)
    at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:106)
    at org.springframework.boot.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:247)
    ... 20 common frames omitted

**Comment by elpauly** [comment]
Hi CoreyBehrends, I have almost the same issue, mine appeared once I updated spring-boot from 1.1.5 to 1.3.2. Were you able to solve yours?

**Comment by elpauly** [comment]
I have find out how to solve this. The problem appeared also when I upgraded the version of spring-boot from 1.1.5 to 1.3.2. The error message was the same. My logback code was:

`<encoder>
       <layout class="org.perf4j.log4j.StatisticsCsvLayout" />
 </encoder>`

So I was using the layout from log4j. I solved it adding an encoder, and using the layout from logback.

`<encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
            <layout class="org.perf4j.logback.StatisticsCsvLayout"/>
 </encoder>`
